project_id = "eumfdhxgwyahphlogbrz"

[functions.view-shared-report]
verify_jwt = false

[functions.independent-learner-signup]
verify_jwt = false

[functions.mpesa-stk-callback]
verify_jwt = false

[functions.lock-expired-scores]
verify_jwt = false

[functions.subscription-lifecycle]
verify_jwt = false

[functions.school-signup-submit]
verify_jwt = false

